project_id = "wsvhmozduyiftmuuynpi"

# Stripe functions (authenticated)
[functions.stripe-payment-methods]
verify_jwt = true

# Shopify functions (public)
[functions.shopify-auth]
verify_jwt = false

[functions.shopify-callback]
verify_jwt = false

[functions.shopify-webhooks]
verify_jwt = false

[functions.shopify-test-api]
verify_jwt = false

[functions.shopify-config-test]
verify_jwt = false

[functions.shopify-private-app]
verify_jwt = false

# Stripe functions from Firebase migration
[functions.stripe-webhook]
verify_jwt = false

# Tracking functions (public for external tracking)
[functions.track-conversion]
verify_jwt = false