
# These are supported funding model platforms

github: [refspring-team]
patreon: refspring
open_collective: refspring
ko_fi: refspring
custom: ['https://refspring.com/sponsor', 'https://buy.stripe.com/refspring']

