// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsvhmozduyiftmuuynpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzdmhtb3pkdXlpZnRtdXV5bnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDQ3OTEsImV4cCI6MjA3MTQyMDc5MX0.eLzX-f5tIJvbqBLB1lbSM0ex1Rz1p6Izemi0NnqiWz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});